In [1]:
1

1

# 大きな表現
## 少し小さな表現
--------------
- 箇条書き
- 箇条書き
--------------
1. 箇条書き
1. 箇条書き

In [2]:
1 + 1

2

In [3]:
5 - 2

3

In [4]:
2 * 3

6

In [5]:
6 / 3

2.0

In [6]:
2 ** 3

8

In [7]:
7 // 3

2

In [8]:
7 % 3

1

In [9]:
# 1 + 1

In [10]:
"A"

'A'

In [11]:
'A'

'A'

In [12]:
type('A')

str

In [13]:
type(1)

int

In [14]:
type(2.4)

float

In [15]:
type(True)

bool

In [16]:
type(False)

bool

In [17]:
1 > 0.89

True

In [18]:
3 < 2

False

In [19]:
x = 100
x

100

In [20]:
x = 293
x

293

In [21]:
y = 50
y

50

In [22]:
x + y

343

In [23]:
(y + 2) * 4

208

In [24]:
def sample_function(data):
    return (data + 2) * 4

In [25]:
sample_function(data=y)

208

In [26]:
sample_function(y)

208

In [27]:
sample_function(3)

20

In [28]:
sample_function(y) + sample_function(3)

228

In [29]:
print(1 + 1)

2


In [30]:
print('今から計算をします:計算結果は', 1 + 1)

今から計算をします:計算結果は 2


In [31]:
1 + 1
1 + 3

4

In [32]:
print(1 + 1)
print(1 + 3)

2
4


In [33]:
print('1.234を丸めた結果', round(1.234))
print('1.963を丸めた結果', round(1.963))

1.234を丸めた結果 1
1.963を丸めた結果 2


In [34]:
round(1.234, ndigits=2)

1.23

In [35]:
print('2.5を丸めた結果', round(2.5))
print('3.5を丸めた結果', round(3.5))

2.5を丸めた結果 2
3.5を丸めた結果 4


In [36]:
round(1.235, ndigits=2)

1.24

In [37]:
class Sample_Class:
    def __init__(self, data1, data2):
        self.data1 = data1
        self.data2 = data2
        
    def method2(self):
        return self.data1 + self.data2

In [38]:
sample_instance = Sample_Class(data1=2, data2=3)
sample_instance.data1

2

In [39]:
sample_instance.method2()

5

In [40]:
data = 1
if (data < 2):
    print('2より小さいデータです')
else:
    print('2以上のデータです')

2より小さいデータです


In [41]:
data = 3
if (data < 2):
    print('2より小さいデータです')
else:
    print('2以上のデータです')

2以上のデータです


In [42]:
for i in range(0, 3):
    print(i)

0
1
2


In [43]:
for i in range(0, 3):
    print('hello')

hello
hello
hello


In [44]:
import numpy as np
import pandas as pd

In [45]:
sample_list = [1, 2, 3, 4, 5]
sample_list

[1, 2, 3, 4, 5]

In [46]:
sample_array = np.array([1, 2, 3, 4, 5])
sample_array

array([1, 2, 3, 4, 5])

In [47]:
np.array([1, 2, 'A'])

array(['1', '2', 'A'], dtype='<U21')

In [48]:
sample_array + 1

array([2, 3, 4, 5, 6])

In [49]:
sample_array * 2

array([ 2,  4,  6,  8, 10])

In [50]:
sample_array_2 = np.array(
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10]])
sample_array_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [51]:
sample_array_2.shape

(2, 5)

In [53]:
np.arange(start=1, stop=6, step=1)

array([1, 2, 3, 4, 5])

In [54]:
np.arange(1, 6, 1)

array([1, 2, 3, 4, 5])

In [55]:
np.arange(start=0.1, stop=0.8, step=0.2)

array([0.1, 0.3, 0.5, 0.7])

In [56]:
np.linspace(start=1, stop=5, num=5)

array([1., 2., 3., 4., 5.])

In [57]:
np.linspace(start=1, stop=5, num=11)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [58]:
np.linspace(start=0.1, stop=0.7, num=4)

array([0.1, 0.3, 0.5, 0.7])

In [59]:
np.tile('A', 5)

array(['A', 'A', 'A', 'A', 'A'], dtype='<U1')

In [60]:
np.tile(0, 4)

array([0, 0, 0, 0])

In [61]:
np.zeros(4)

array([0., 0., 0., 0.])

In [62]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [63]:
np.ones(3)

array([1., 1., 1.])

In [64]:
d1_array = np.array([1, 2, 3, 4, 5])
d1_array

array([1, 2, 3, 4, 5])

In [65]:
d1_array[0]

1

In [66]:
d1_array[[1, 2]]

array([2, 3])

In [67]:
d1_array[1:3]

array([2, 3])

In [68]:
d1_array[[0, 4]]

array([1, 5])

In [69]:
d2_array = np.array(
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10]])
d2_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [70]:
d2_array[0, 3]

4

In [71]:
d2_array[1, 2:4]

array([8, 9])

In [73]:
sample_df = pd.DataFrame({
    'col1' : sample_array,
    'col2' : sample_array * 2,
    'col3' : ['A', 'B', 'C', 'D', 'E']
})
print(sample_df)

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E


In [74]:
sample_df

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E

In [77]:
file_data = pd.read_csv('2-4-1-sample_data.csv')
file_data

col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C

In [78]:
df_1 = pd.DataFrame({
    'col1' : np.array([1, 2, 3]),
    'col2' : np.array(['A', 'B', 'C'])
})

df_2 = pd.DataFrame({
    'col1' : np.array([4, 5, 6]),
    'col2' : np.array(['D', 'E', 'F'])
})

In [79]:
pd.concat([df_1, df_2])

col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F

In [80]:
pd.concat([df_1, df_2], axis=1)

col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F

In [81]:
sample_df.col2

0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int64

In [82]:
sample_df['col2']

0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int64

In [83]:
sample_df[['col2', 'col3']]

col2 col3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    E

In [84]:
sample_df

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E

In [85]:
sample_df.drop('col1', axis=1)

col2 col3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    E

In [86]:
sample_df.head(n=3)

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C

In [87]:
sample_df.query('index == 0')

col1  col2 col3
0     1     2    A

In [88]:
sample_df.query('col3 == "A"')

col1  col2 col3
0     1     2    A

In [89]:
sample_df.query('col3 == "A" | col3 == "D"')

col1  col2 col3
0     1     2    A
3     4     8    D

In [90]:
sample_df.query('col3 == "A" & col1 == 3')

Empty DataFrame
Columns: [col1, col2, col3]
Index: []

In [91]:
sample_df.query('col3 == "A"')[['col2', 'col3']]

col2 col3
0     2    A

In [92]:
type(sample_df)

pandas.core.frame.DataFrame

In [94]:
type(sample_df['col1'])

pandas.core.series.Series

In [95]:
type(np.array(sample_df['col1']))

numpy.ndarray

In [96]:
type(sample_df['col1'].to_numpy())

numpy.ndarray

In [97]:
sample_df['col1'].to_numpy()

array([1, 2, 3, 4, 5])

In [98]:
help(sample_df.query)

Help on method query in module pandas.core.frame:

query(expr: 'str', *, inplace: 'bool' = False, **kwargs) -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Query the columns of a DataFrame with a boolean expression.
    
    Parameters
    ----------
    expr : str
        The query string to evaluate.
    
        You can refer to variables
        in the environment by prefixing them with an '@' character like
        ``@a + b``.
    
        You can refer to column names that are not valid Python variable names
        by surrounding them in backticks. Thus, column names containing spaces
        or punctuations (besides underscores) or starting with digits must be
        surrounded by backticks. (For example, a column named "Area (cm^2)" would
        be referenced as ```Area (cm^2)```). Column names which are Python keywords
        (like "list", "for", "import", etc) cannot be used.
    
        For example, if one of your columns is called ``a a`` and y